### ISSUE TITLE
Arcane Recovery should be limited to Spell Slots smaller than 6, not including 6

### ISSUE THREAD

**Issue by itteerde** [krbz999/zhell-macros#1]
Arcane Recovery should be limited to Spell Slots smaller than 6, not including 6

fixed it for our table, just wanted to let you know if you want to fix it here, too

![image](https://github.com/krbz999/zhell-macros/assets/8367477/78bc8133-33fd-4bcd-abaa-751f970cd914)

**Comment by krbz999** [comment]
Updated macro to be more configurable, as well as for allowing pact slots to be recovered.
